# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e23d2ce0ca8f32de8ee7ddd6f3be3994e5cd958a2ac467a767ebd79ce4bdade9913e880aee5ccc611159bdf0ba5bc5c8a7855e0c032f8219ab5d77150f8e228

test:
  secret_key_base: 7e0eadc7b11f7b84c6ebbba796698bd09b5ba8c1ef2b303153852625970440dc8148174472399912f0489a95cbf448ba7a105fc174f7e4469a1aada1e8c08a5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
